language: java

services:
- docker
cache:
  directories:
  - "$HOME/.cache"
  
before_install:
  - chmod +x mvnw
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B

env:
  global:
    - PCKCLOUD_TOKEN: 14eb87ed18ebe535fddbf9880b0b4f56d723266d0fc32c9d #packagecloud.io
    - GITHUB_TOKEN: "5adc2bc01f814f242bb87b09d8a21316f29812ea" #ci
    - SPRING_PROFILES_ACTIVE: cloud

before_deploy:
  - echo 'before_deploy:....'
  - git config --local user.name "jsimao71"
  - git config --local user.email "jsimao71@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
# - provider: script
#   script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  - provider: releases
    api_key: "5adc2bc01f814f242bb87b09d8a21316f29812ea"
    file: "$TRAVIS_BUILD_DIR/target/einnovator-util-1.5.17.0.RELEASE.jar"
    skip_cleanup: true
    draft: true
    overwrite: true
    #on:
    # tags: true   
  - provider: packagecloud
    repository: "einnovator"
    username: "einnovator"
    file: "$TRAVIS_BUILD_DIR/target/einnovator-util-1.5.17.0.RELEASE.jar"
    token: "$PCKCLOUD_TOKEN"
    draft: true
    #on:
    # tags: true
    #dist: "ubuntu/precise"
    skip_cleanup: true
    overwrite: true
  
after_deploy: 
  - "echo 'Deployment Done!'"
